debian package for frontend - added postinst, postrm, prerm, control, and data

diff --git a/webapp/src/deb/control/postinst b/webapp/src/deb/control/postinst
--- a/webapp/src/deb/control/postinst
+++ b/webapp/src/deb/control/postinst
@@ -1,6 +1,60 @@
 #!/bin/sh
-if [ -e "/etc/unifiedviews/backend-config.properties" ]; then
-    mv /usr/share/unifiedviews/webapp/WEB-INF/config.properties /usr/share/unifiedviews/webapp/WEB-INF/config.properties.save
-    ln -s /etc/unifiedviews/backend-config.properties /usr/share/unifiedviews/webapp/WEB-INF/config.properties
-fi
-service tomcat7 restart
+# postinst script for #PACKAGE#
+#
+# see: dh_installdeb(1)
+
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
+case "$1" in
+    configure)
+    
+    if [ -e "/etc/unifiedviews/frontend-config.properties" ]; then
+        if  [ -e "/usr/share/unifiedviews/webapp/WEB-INF/config.properties" ]; then
+            mv /usr/share/unifiedviews/webapp/WEB-INF/config.properties /usr/share/unifiedviews/webapp/WEB-INF/config.properties.save
+        fi
+        
+        ln -s /etc/unifiedviews/frontend-config.properties /usr/share/unifiedviews/webapp/WEB-INF/config.properties
+    fi
+
+    
+    # todo /var/lib/unifiedviews/target/dpu
+    mkdir -p /var/log/unifiedviews/frontend
+    chown tomcat7:tomcat7 /var/log/unifiedviews/frontend
+    mkdir -p /usr/share/unifiedviews/webapp
+    chown tomcat7:tomcat7 /usr/share/unifiedviews/webapp
+    
+    service tomcat7 restart
+
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
+
+
+
