nicely formated postinst, postrm, prerm for backend .deb

diff --git a/backend/src/deb/control/postinst b/backend/src/deb/control/postinst
--- a/backend/src/deb/control/postinst
+++ b/backend/src/deb/control/postinst
@@ -1,4 +1,22 @@
 #!/bin/sh
+# postinst script for #PACKAGE#
+#
+# see: dh_installdeb(1)
+
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 . /usr/share/debconf/confmodule
 
 
@@ -109,7 +127,16 @@ case "$1" in
   ;;
 
   *)
-    echo "$0 called with unknown argument \`$1'" >&2
+    echo "postinst called with unknown argument \`$1'" >&2
     exit 1
+    
   ;;
 esac
+
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
